version: 2
project_name: jira

release:
  prerelease: auto
  name_template: "{{.Tag}}"
  draft: false
  mode: "replace"

builds:
  - main: ./cmd/jira
    binary: jira
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/ankitpokhrel/jira-cli/internal/version.Version={{.Version}}
      - -X github.com/ankitpokhrel/jira-cli/internal/version.GitCommit={{.FullCommit}}
      - -X github.com/ankitpokhrel/jira-cli/internal/version.SourceDateEpoch={{.CommitTimestamp}}

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

homebrew_casks:
  - name: jira
    repository:
      owner: iatsiuk
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/iatsiuk/jira-cli"
    description: "Interactive command-line tool for Jira"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
